// <auto-generated />
using System;
using Duplicate.Identifier.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Duplicate.Identifier.Migrations
{
    [DbContext(typeof(DuplicateDbContext))]
    [Migration("20250615120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Duplicate.Identifier.Db.DbItemIngestion", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IngestionTime")
                        .HasColumnType("DATETIME");


                    b.HasIndex("ItemId");

                    b.ToTable("ItemIngestion", (string)null);
                });

            modelBuilder.Entity("Duplicate.Identifier.Db.DbScanResults", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("FinishTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("LastModificationDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("ScanResults");
            });
#pragma warning restore 612, 618
        }
    }
}
